### ISSUE TITLE
RuneAudio is a dead project. What are the alturnatives?

### ISSUE THREAD

**Issue by mecworks** [RuneAudio/Docs#29]
With no real development, no bug fixes or enhancements in 4-6 years, it looks like RuneAudio is officially dead.  What are the alternatives?

**Comment by ACXgit** [comment]
Hi, what's the purpose of this issue? It's not useful ([looking for alternatives?](https://lmgtfy.com/?q=runeaudio+alternatives)) nor polite.
Btw, RuneAudio is far from being a dead project - v2.0 is in the works.

**Comment by mecworks** [comment]
How is one to know that v2.0 is in the works?  I can find no indication on the web site, the forum is filled with posts of barely maintained and/or hacked versions but no announcements of betas or testing of v2.0 and there have been no commits in github for years.

There should be some updates to the web site that are plain and easy to see that indicate RuneAudio has a future and a road map.  There should be some official announcements of releases and beta testing leading up to 2.0.  If this isn't the project for 2.0, then maybe some documentation here that explains that and a link to the new repo would be a good thing.  

Once it's easier to know about the future, less questions like this will be asked and the more help you'll get in developing and testing v2.0.

**Comment by technosf** [comment]
I think, if one steps back from the situation, there is no sign of life in the Rune repo, nor in the forums from the dev's. To any outside (of core Dev) observer, the project look like other dead projects, regardless of any work going on behind the scenes.

This speaks to perhaps underlying issues with the project, where development is slow because it is not inclusive, with the work happening, unseen, in a private repo.

Similarly, the apparent historical implicit obfuscation of the system, making it near impossible to build independently by tying the system to a custom build of an Arch image, rather than splitting the OS from the app and enabling wider development and contributions by the community.

**Comment by mecworks** [comment]
I agree.  The perception is that the project is not moving forward and with no visible development or open development on the forums, no roadmap of features and no projected release schedule, there is no way of seeing this as anything other than inactive.

What I'd need to see to believe that there is a future is:

1. Updates pushed to the public repo
2. Updates to the web site with a roadmap and specific planned release dates.
3. Public beta of current builds with a feedback area on the forums
4. Official releases of betas on on the web site.

**Comment by rastus101** [comment]
The RuneAudio website and Forum is offline?

**Comment by ACXgit** [comment]
Website and forum are up again, we had a technical problem with the provider. Sorry for the inconvenience.

**Comment by ghost** [comment]
@ACXgit so the last time you did anything was 2020 to comment that there v2 in the works.
Would you mind releasing what you have done so far or is your intent to keep that closed course and just not update anyone on the development? It sounds like you should hand this over to the community with time and passion for such projects, you don't seem to have either.
